[package]
name = "pinocchio-small-oracle-shared-bench"
version = "0.1.0"
edition = "2021"

[lib]
name = "pinocchio_small_oracle_shared_bench"
crate-type = ["rlib"]

[dependencies]
pinocchio-small-oracle-shared-types = { path = "../shared-types" }
mollusk-svm = "0.0.12"
solana-sdk = "2.1"
