[package]
name = "pinocchio-small-oracle-shared-types"
version = "0.1.0"
edition = "2021"

[lib]
name = "pinocchio_small_oracle_shared_types"
crate-type = ["rlib"]

[dependencies]
pinocchio = { workspace = true }
